require 'rubygems'
require 'sinatra'
require 'weixin/model'
require 'weixin/middleware'
require 'net/http'
require 'nokogiri'
require 'restclient'
require 'open-uri'
require File.join(File.dirname(__FILE__),'private')
require File.join(File.dirname(__FILE__),'..','main')
